### PR TITLE
correct my weather update fix

### PR DESCRIPTION
**Pull request by pantgr**
The old command call the $customWxFile to update the weather file but in while (truth) loop never update returns the same , if the weather files don't updated of any other part of the code my fix is correct.

### CODE REVIEW

**Comment by allebb** [comment]
This PR can be closed now, right? The issue was caused by an issue with your manually entered TTS string formatting correct?

**Comment by allebb** [comment]
Sorry, I don't understand your message. Are you saying that this *still*
needs to be merged in order to fix the issue you're having?

Have you checked that this "fix" doesn't affect the other features? - If
not, I'm going to have to hold off merging this particular request until
the weekend so that I can fully regression test etc.

**Comment by pantgr** [comment]
yes , needs to be merged in order to fix the issue you're have , works now 2 days with no problem

**Comment by allebb** [comment]
Sorry for the delay in getting to this PR but I'm off for two weeks as of Monday and so will be doing massive improvements to Pirrot during that time - I'll also review and merge this PR too.

Let me know if there is anything you'd like to see implemented or updated in Pirrot too as I will plan to get these done and released before July!

Cheers,
Bobby

**Comment by pantgr** [comment]
hi allebb , The pirrot now works very nice no problems at all i tested so long , only one thing make pirrot to crash, if not have a internet connection and try to get the weather update stop with ptt on forever, need a little care about this, except this one work very stable :-) you make very good job thanks you again. One nice option as update is to get weather predictions for next days or the ability to set the user if like the current weather data or weather predictions or both . One more that cams to my mine is a alert system that help ppl on natural disasters etc, with custom voice messages or text to speech messages in loop, if used on free public pmr frequencies, with alert activation immediately to stop the normal functionality and loop the alert messages only . 

Thanks again , very good job

**Pull request merged**
